---
- hosts: localhost
  user: ubuntu
  tasks:   
    - name: Configure AWS ACCESS KEY ID
      command: aws configure set aws_access_key_id "{{AWS_ACCESS_KEY_ID}}"

    - name: Configure AWS SECRET ACCESS KEY 
      command: aws configure set aws_secret_access_key "{{AWS_SECRET_ACCESS_KEY}}"
    
    - name: Get AWS ECR Login 
      shell: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URL
        
    - name: Push Docker Image to ECR
      command: docker push "{{ECR_URL}}/{{ECR_REPO}}:{{DOCKER_IMAGE}}_latest"

    - name: Remove Docker Image Origin
      command: docker image rm "{{DOCKER_IMAGE}}:{{DOCKER_TAG}}"
    
    - name: Remove Docker Image ECR
      command: docker image rm "{{ECR_URL}}/{{ECR_REPO}}:{{DOCKER_IMAGE}}_latest"
                


    
