---
- hosts: 192.168.1.16
  become: yes
  tasks:          
    - name: Copy file
      copy:
        src: Dockerfile
        dest: /home/ubuntu/
    - name: Copy file web page
      copy:
        src: web
        dest: /home/ubuntu/

    - name: Build Docker Image
      command: sudo docker build -t  "{{DOCKER_IMAGE}}" /home/ubuntu/

   
   
                


    
